"""
RAGAS Testing Module
====================
This module provides functionality for evaluating RAG (Retrieval-Augmented Generation)
systems using the RAGAS framework.

RAGAS metrics include:
- Faithfulness: Measures factual consistency of the answer with the context
- Answer Relevancy: Measures how relevant the answer is to the question
- Context Precision: Measures signal-to-noise ratio in retrieved contexts
- Context Recall: Measures if all relevant information was retrieved
"""

import os
from typing import List, Dict, Any
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)


def create_ragas_dataset(
    questions: List[str],
    answers: List[str],
    contexts: List[List[str]],
    ground_truths: List[str] = None
) -> Dataset:
    """
    Create a dataset for RAGAS evaluation.
    
    Args:
        questions: List of questions asked
        answers: List of generated answers
        contexts: List of retrieved context chunks (each is a list of strings)
        ground_truths: Optional list of reference answers
        
    Returns:
        Dataset object compatible with RAGAS
    """
    data = {
        "question": questions,
        "answer": answers,
        "contexts": contexts,
    }
    
    if ground_truths:
        data["ground_truth"] = ground_truths
    
    return Dataset.from_dict(data)


def evaluate_rag_system(
    questions: List[str],
    answers: List[str],
    contexts: List[List[str]],
    ground_truths: List[str] = None,
    metrics: List[Any] = None
) -> Dict[str, float]:
    """
    Evaluate a RAG system using RAGAS metrics.
    
    Args:
        questions: List of questions
        answers: List of generated answers
        contexts: List of retrieved contexts
        ground_truths: Optional reference answers
        metrics: List of RAGAS metrics to use (default: all available)
        
    Returns:
        Dictionary containing evaluation scores
    """
    # Default metrics
    if metrics is None:
        metrics = [faithfulness, answer_relevancy]
        if ground_truths:
            metrics.extend([context_precision, context_recall])
    
    # Create dataset
    dataset = create_ragas_dataset(questions, answers, contexts, ground_truths)
    
    # Run evaluation
    results = evaluate(dataset, metrics=metrics)
    
    return results


def run_example_evaluation():
    """
    Run an example RAGAS evaluation with needle-in-a-haystack queries.
    """
    # Needle-in-a-haystack test queries
    questions = [
        "What is the claim date?",      
        "What is the claim amount?",
        "When was the incident reported?",
        "When did the incident occur?",
        "How many days elapsed between the incident date and when the claim was filed?"
        "What is the exact purchase order number referenced for the February 5–12, 2024 maintenance work that allegedly addressed the water intrusion?",
        "According to the chronological event timeline, at what precise time did the morning shift supervisor discover water pooling in the basement mechanical room and second‑floor production area on March 12, 2024?",         
        "In the March 14, 2024 loss assessor's preliminary assessment, what percentage of the facility is estimated to be affected by damage?",     
        "Summarize the entire insurance claim case",     
        "What is the complete chronological timeline of all major events from the initial February seepage observations through the anticipated resolution dates, including inspections, reports, and claim-handling milestones?",
        "What are the main coverage, documentation, and causation issues identified in the claim, and how might they affect the insurer’s final decision on property damage and business interruption payments?"

    ]
    
    # You'll need to provide answers generated by your RAG system
    answers = [
        # TODO: Replace with actual answers from your RAG system
        "The claim was filed on March 15, 2024 at 11:00 AM.",
        "The claim amount is $387,500.00.",   
        "The incident was reported on March 15, 2024, at 11:00 AM.",
        "The incident occurred on March 12, 2024 at 2:47 AM.",
        "The exact duration between the incident date and when the claim was filed is 3 days, 8 hours, and 13 minutes, totaling 80.22 hours.",        
        "The loss location is 2847 Industrial Drive, Newark, NJ 07105.",
        "The morning shift supervisor discovered water pooling in the basement mechanical room and second-floor production area on March 12, 2024, at 6:30 AM.",
        "The loss assessor's preliminary assessment on March 14, 2024, estimating 15-20% of the facility to be affected by damage, was conducted within the 2-day deadline after the incident on March 12, 2024.",
        
    ]
    
    # Get additional answers and concatenate to the answers list
    answers += get_addional_answers()
    
    # Contexts retrieved from rag_context file
    contexts = [[
  "*\n\n**March 15, 2024 - 11:00 AM**\n\n\n- Formal claim filed with all parties (claimant, adjuster, assessor,\ncarrier).",
  "- Photo dates appear inconsistent (some labeled March 12; others lack\ntimestamps; one appears to be from 2023 based on calendar in background).\n- *Concern flagged: Photo verification pending.*\n\n**March 15, 2024 - 11:00 AM**",
  "| March 25 | Structural and engineering assessments due |\n| March 28 | Public adjuster revised damage estimate due |\n| March 31 | All outstanding documentation deadline |\n| April 5 | Internal claim review meeting |\n| April 12 | Coverage determination notice to claimant |\n| April 19 | Final claim decision and payment/denial notice |\n\n---\n\n## CLAIM CLASSIFICATION & RISK FACTORS\n\n**Claim Complexity Level:** HIGH\n**Investigation Risk Rating:** ELEVATED\n\n**Risk Factors Identified:**\n\n1.",
  "records (Feb-March)\n- ☐ Customer order documentation and cancellation records\n- ☐ Photo metadata authentication\n- ☐ Competitive repair quotes (minimum 3)\n- ☐ Staff interviews regarding timeline and operational impact\n\n### **Decision Timeline**\n\n| Date | Milestone |\n|------|-----------|\n| March 22 | Moisture testing report due |",
  "called to premises.\n- Arrival time: Claimed as \"approximately 11:00 AM\" by claimant; 11:47 AM\nper their invoice timestamp.\n- Initial water removal and assessment began.\n\n**March 13, 2024 - 8:00 AM**\n- Claimant submitted preliminary claim notice to insurance carrier.\n- Estimated damage: $387,500 (basis for estimate not explained).\n- Claim described as \"catastrophic water damage affecting 60% of\nfacility.\"",
  "- *Note: No photos taken. No dates recorded in maintenance log.*\n\n**February 5-12, 2024**\n- Period during which maintenance allegedly addressed water intrusion.\nExact dates and methods unclear.\n- Purchase order #PR-2847 issued but vendor name partially illegible in\ncopy provided.\n- *Note: Invoice not yet submitted. Vendor contact information\nunavailable.*\n\n**February 18, 2024**\n- Claimant reports roof inspection conducted. Inspector identification\nunknown."
],
[
  "deferred\n- Bank deposits for March show $67,000 (contradicting the $100,000 loss\nclaim)\n- *Note: Claimant states some customers paid deposits in advance; amounts\nunclear.*\n- Payroll records partially provided (only February full records; March\nrecords \"in accounting department\")",
  "*\n\n**March 15, 2024 - 11:00 AM**\n\n\n- Formal claim filed with all parties (claimant, adjuster, assessor,\ncarrier).",
  "- **If cause = sudden/external:** Likely covered; proceed with damage\nassessment\n- **If cause = negligent prior repair:** May invoke maintenance breach;\nreduce coverage\n- **If cause = unknown/undeterminable:** Request additional\ninvestigation; consider coverage dispute\n- **Property damage claim:** Approve within policy limits once cause\ndetermined (likely $150K-$250K range)\n- **Business interruption claim:** Reduce to $35K-$50K based on financial\nrecord conflicts\n\n**Estimated Timeline to Resolution:** 3-4 weeks (contingent on completion\nof pending assessments)\n\n---\n\n## APPENDIX A: POLICY COVERAGE SUMMARY\n\n**Policy Number:** CP-4827-2023\n**Policyholder:** Precision Manufacturing Ltd.\n**Coverage Period:** January 1, 2024 - December 31, 2024\n**Premium:** $42,750 (annual)\n\n**Coverage Sections:**\n1. Building/Structure: $1,200,000 limit\n2. Contents/Equipment: $800,000 limit\n3. Work-in-Progress Inventory: $150,000 limit\n4. Business Interruption: $100,000 limit\n5. Emergency Mitigation: $50,000 limit\n\n**Deductibles:**\n- Property: $25,000\n- Business Interruption: 7-day waiting period\n- Mitigation: $5,000\n\n**Exclusions:**\n- Flood damage (separate policy required)\n- Maintenance-related damage (if preventive measures not taken)\n- Undisclosed pre-existing conditions\n\n---\n\n## APPENDIX B: DOCUMENT CHAIN OF CUSTODY\n\n| Document | Provided By | Date Received | Status |\n|----------|-------------|---------------|--------|\n| Initial incident report | Claimant | March 13 | Received - incomplete |\n| Maintenance records | Claimant | March 14 | Partial (3 of 5 expected) |\n| Water mitigation invoice | QuickDry/Flow Services | March 14 | 2 of 3\nreceived |\n| Photographic evidence | Claimant | March 14 | Received - metadata\nverification pending |\n| Public adjuster estimate | Adjuster (Mark T.) | March 15 | Received -\nunder review |\n| Insurance assessor report | Jennifer K.",
  "Do\nnot approve claim until cause of loss is determined.\"*\n\n### **Public Adjuster Statement (Mark T., March 13)**\n\n*\"Client's loss is clearly within policy limits. Insurance company\ntactics of delaying payment are harming business operations. Water damage\nis extensive and business interruption ongoing. Estimate of $387,500 is\nconservative given market replacement costs. Demand immediate payment\npending detailed assessment.\"*\n\n### **Claimant Statement (submitted March 13)**\n\n*\"We have been good-faith customers for three years with no prior claims.\""
],
[
  "**March 12, 2024 - 2:47 AM** *(Primary Loss Event)*\n- Overnight water intrusion event discovered when morning shift arrived\nat 6:30 AM.\n- Extent of damage: Unknown until post-incident inspection (see March 13-\n14 events).\n- Source of water: \"Undetermined\" per initial incident report.",
  "The claimant reports\nbusiness interruption losses exceeding typical seasonal patterns, but\nsupporting documentation is incomplete and timelines are unclear.\n\n---\n\n## CHRONOLOGICAL EVENT TIMELINE\n\n### **February 2024 Events**\n\n**February 3, 2024 - 10:15 AM**\n- Building maintenance staff (name redacted in report) observed minor\nwater seepage in basement mechanical room near west wall.\n- No formal incident report filed. Verbal notification only to building\nsupervisor.\n- *Note: No photos taken. No dates recorded in maintenance log.",
  "| Initial incident report | Claimant | March 13 | Received - incomplete |\n| Maintenance records | Claimant | March 14 | Partial (3 of 5 expected) |\n| Water mitigation invoice | QuickDry/Flow Services | March 14 | 2 of 3\nreceived |\n| Photographic evidence | Claimant | March 14 | Received - metadata\nverification pending |\n| Public adjuster estimate | Adjuster (Mark T.) | March 15 | Received -\nunder review |\n| Insurance assessor report | Jennifer K.",
  "| March 15 | Received |\n| Roof inspection notes | Claimant | March 16 | Handwritten only -\nunclear |\n\n\n| Financial records | Claimant | March 16 | Incomplete - February full,\nMarch partial |\n\n---\n\n**Case File Compiled By:** Claims Investigation Department\n**Date Compiled:** March 16, 2024\n**Next Review Date:** March 22, 2024\n**Assigned Investigator:** [Name redacted]\n**File Status:** OPEN - ACTIVE INVESTIGATION",
  "The March 12 event was sudden and severe. We acted quickly to mitigate\nfurther damage. The $387,500 figure represents our honest assessment of\nlosses. We do not understand why the insurance assessor is questioning\nthe damage when photos are provided. We need funds immediately to restart\noperations.\"*\n\n---\n\n## INVESTIGATION STATUS & NEXT STEPS\n\n### **Completed Actions**\n- ✓ Preliminary claim filing (March 13)\n- ✓ Initial loss assessor inspection (March 14)\n- ✓ Emergency mitigation services engaged (March 12)\n-",
  "- Immediate action: Power shut-off to affected areas. No emergency water\nmitigation company called until 10:30 AM (4-hour delay).\n- *Unresolved question: Was this delay necessary? Claimant states\n\"awaiting approval,\" but no documentation of approval request exists.*\n\n**March 12, 2024 - 10:30 AM**\n- Emergency response company (name partially obscured: \"QuickDry\nServices\" or \"QuickFlow Services\"?) called to premises."
],
[
  "The claimant reports\nbusiness interruption losses exceeding typical seasonal patterns, but\nsupporting documentation is incomplete and timelines are unclear.\n\n---\n\n## CHRONOLOGICAL EVENT TIMELINE\n\n### **February 2024 Events**\n\n**February 3, 2024 - 10:15 AM**\n- Building maintenance staff (name redacted in report) observed minor\nwater seepage in basement mechanical room near west wall.\n- No formal incident report filed. Verbal notification only to building\nsupervisor.\n- *Note: No photos taken. No dates recorded in maintenance log.",
  "**March 12, 2024 - 2:47 AM** *(Primary Loss Event)*\n- Overnight water intrusion event discovered when morning shift arrived\nat 6:30 AM.\n- Extent of damage: Unknown until post-incident inspection (see March 13-\n14 events).\n- Source of water: \"Undetermined\" per initial incident report.\nPossibilities include:\n  - Roof failure (west section)\n  - Plumbing rupture (third-floor bathroom area - location uncertain)\n  - HVAC condensation drain backup\n  - Exterior wall crack\n  - *Note: No clear evidence points to single cause. Building has never\nhad formal engineering survey.*\n\n**March 12, 2024 - 6:30 AM**\n- Morning shift supervisor discovered water pooling in basement\nmechanical room and on second-floor production area.\n- Immediate action: Power shut-off to affected areas. No emergency water\nmitigation company called until 10:30 AM (4-hour delay).\n- *Unresolved question: Was this delay necessary? Claimant states\n\"awaiting approval,\" but no documentation of approval request exists.*\n\n**March 12, 2024 - 10:30 AM**\n- Emergency response company (name partially obscured: \"QuickDry\nServices\" or \"QuickFlow Services\"?) called to premises.\n- Arrival time: Claimed as \"approximately 11:00 AM\" by claimant; 11:47 AM\nper their invoice timestamp.\n- Initial water removal and assessment began.\n\n**March 13, 2024 - 8:00 AM**\n- Claimant submitted preliminary claim notice to insurance carrier.\n- Estimated damage: $387,500 (basis for estimate not explained).\n- Claim described as \"catastrophic water damage affecting 60% of\nfacility.\"\n\n**March 13, 2024 - 2:15 PM**\n- Claimant's public adjuster, Mark T. [Last name redacted], appointed.\n- Public adjuster immediately disputed initial damage assessment as\n\"underestimated.\"\n- New estimate requested but not yet provided as of March 15.\n\n**March 14, 2024 - 9:00 AM**\n- Insurance company's loss assessor, Jennifer K. [Last name redacted],\ninspected facility.",
  "The March 12 event was sudden and severe. We acted quickly to mitigate\nfurther damage. The $387,500 figure represents our honest assessment of\nlosses. We do not understand why the insurance assessor is questioning\nthe damage when photos are provided. We need funds immediately to restart\noperations.\"*\n\n---\n\n## INVESTIGATION STATUS & NEXT STEPS\n\n### **Completed Actions**\n- ✓ Preliminary claim filing (March 13)\n- ✓ Initial loss assessor inspection (March 14)\n- ✓ Emergency mitigation services engaged (March 12)\n-",
  "(PML)\n**Policy Number:** CP-4827-2023\n**Claim Date Filed:** March 15, 2024\n**Incident Date:** March 12, 2024\n**Location:** 2847 Industrial Drive, Newark, NJ 07105\n**Claim Amount:** $387,500 (Initial estimate; under investigation)\n**Status:** Pending - Additional documentation required\n\nThis claim involves partial water damage to a three-story manufacturing\nfacility following an undetermined plumbing event."
],

[
  "*\n\n**March 15, 2024 - 11:00 AM**\n\n\n- Formal claim filed with all parties (claimant, adjuster, assessor,\ncarrier).",
  "- Photo dates appear inconsistent (some labeled March 12; others lack\ntimestamps; one appears to be from 2023 based on calendar in background).\n- *Concern flagged: Photo verification pending.*\n\n**March 15, 2024 - 11:00 AM**",
  "records (Feb-March)\n- ☐ Customer order documentation and cancellation records\n- ☐ Photo metadata authentication\n- ☐ Competitive repair quotes (minimum 3)\n- ☐ Staff interviews regarding timeline and operational impact\n\n### **Decision Timeline**\n\n| Date | Milestone |\n|------|-----------|\n| March 22 | Moisture testing report due |",
  "| Initial incident report | Claimant | March 13 | Received - incomplete |\n| Maintenance records | Claimant | March 14 | Partial (3 of 5 expected) |\n| Water mitigation invoice | QuickDry/Flow Services | March 14 | 2 of 3\nreceived |\n| Photographic evidence | Claimant | March 14 | Received - metadata\nverification pending |\n| Public adjuster estimate | Adjuster (Mark T.) | March 15 | Received -\nunder review |\n| Insurance assessor report | Jennifer K.",
  "| March 15 | Received |\n| Roof inspection notes | Claimant | March 16 | Handwritten only -\nunclear |\n\n\n| Financial records | Claimant | March 16 | Incomplete - February full,\nMarch partial |\n\n---\n\n**Case File Compiled By:** Claims Investigation Department\n**Date Compiled:** March 16, 2024\n**Next Review Date:** March 22, 2024\n**Assigned Investigator:** [Name redacted]\n**File Status:** OPEN - ACTIVE INVESTIGATION",
  "| March 25 | Structural and engineering assessments due |\n| March 28 | Public adjuster revised damage estimate due |\n| March 31 | All outstanding documentation deadline |\n| April 5 | Internal claim review meeting |\n| April 12 | Coverage determination notice to claimant |\n| April 19 | Final claim decision and payment/denial notice |\n\n---\n\n## CLAIM CLASSIFICATION & RISK FACTORS\n\n**Claim Complexity Level:** HIGH\n**Investigation Risk Rating:** ELEVATED\n\n**Risk Factors Identified:**\n\n1."
],

[
  "**March 12, 2024 - 2:47 AM** *(Primary Loss Event)*\n- Overnight water intrusion event discovered when morning shift arrived\nat 6:30 AM.\n- Extent of damage: Unknown until post-incident inspection (see March 13-\n14 events).\n- Source of water: \"Undetermined\" per initial incident report.\nPossibilities include:\n  - Roof failure (west section)\n  - Plumbing rupture (third-floor bathroom area - location uncertain)\n  - HVAC condensation drain backup\n  - Exterior wall crack\n  - *Note: No clear evidence points to single cause. Building has never\nhad formal engineering survey.*\n\n**March 12, 2024 - 6:30 AM**\n- Morning shift supervisor discovered water pooling in basement\nmechanical room and on second-floor production area.\n- Immediate action: Power shut-off to affected areas. No emergency water\nmitigation company called until 10:30 AM (4-hour delay).\n- *Unresolved question: Was this delay necessary? Claimant states\n\"awaiting approval,\" but no documentation of approval request exists.*\n\n**March 12, 2024 - 10:30 AM**\n- Emergency response company (name partially obscured: \"QuickDry\nServices\" or \"QuickFlow Services\"?) called to premises.\n- Arrival time: Claimed as \"approximately 11:00 AM\" by claimant; 11:47 AM\nper their invoice timestamp.\n- Initial water removal and assessment began.\n\n**March 13, 2024 - 8:00 AM**\n- Claimant submitted preliminary claim notice to insurance carrier.\n- Estimated damage: $387,500 (basis for estimate not explained).\n- Claim described as \"catastrophic water damage affecting 60% of\nfacility.\"\n\n**March 13, 2024 - 2:15 PM**\n- Claimant's public adjuster, Mark T. [Last name redacted], appointed.\n- Public adjuster immediately disputed initial damage assessment as\n\"underestimated.\"\n- New estimate requested but not yet provided as of March 15.\n\n**March 14, 2024 - 9:00 AM**\n- Insurance company's loss assessor, Jennifer K. [Last name redacted],\ninspected facility.",
  "The claimant reports\nbusiness interruption losses exceeding typical seasonal patterns, but\nsupporting documentation is incomplete and timelines are unclear.\n\n---\n\n## CHRONOLOGICAL EVENT TIMELINE\n\n### **February 2024 Events**\n\n**February 3, 2024 - 10:15 AM**\n- Building maintenance staff (name redacted in report) observed minor\nwater seepage in basement mechanical room near west wall.\n- No formal incident report filed. Verbal notification only to building\nsupervisor.\n- *Note: No photos taken. No dates recorded in maintenance log.",
  "[Last name redacted],\ninspected facility.\n- Visual assessment only; no moisture readings taken at that time.\n- Assessor noted \"inconsistencies in claimant's account of water path.\"\n- Preliminary assessment: Damage confined to basement and small portion\nof second floor (estimated 15-20% of facility).\n\n**March 14, 2024 - 3:30 PM**\n- Claimant provided photographic evidence of water damage.",
  "Inspector identification\nunknown.\n- Preliminary report mentioned \"potential vulnerability in roof seams,\nwest side.\"\n- Original inspection report not provided; only handwritten notes from\nsite manager.\n\n**February 22, 2024**\n- Water seepage reportedly reappeared. No photographs.\n- Building occupants relocated from second floor production area \"for\nseveral days.\" Exact duration not specified.\n- Estimated loss of production: \"approximately $25,000\" (no supporting\ncalculations).\n\n### **March 2024 Events**"
],

 [
  "- West wall seepage (Feb) could be separate from overhead water (March\n12).\n   - Plumbing third floor not yet inspected.\n   - *Resolution needed: Plumbing assessment + structural inspection*\n\n2. **Extent of Damage Discrepancy:**\n   - Claimant claims 60% of facility affected.\n   - Insurance assessor estimates 15-20%.\n   - Public adjuster claims \"closer to 40%.\"\n   - *Resolution needed: Moisture mapping + structural survey*\n\n3.",
  "[Last name redacted],\ninspected facility.\n- Visual assessment only; no moisture readings taken at that time.\n- Assessor noted \"inconsistencies in claimant's account of water path.\"\n- Preliminary assessment: Damage confined to basement and small portion\nof second floor (estimated 15-20% of facility).\n\n**March 14, 2024 - 3:30 PM**\n- Claimant provided photographic evidence of water damage.",
  "- Claim described as \"catastrophic water damage affecting 60% of\nfacility.\"\n\n**March 13, 2024 - 2:15 PM**\n- Claimant's public adjuster, Mark T. [Last name redacted], appointed.\n- Public adjuster immediately disputed initial damage assessment as\n\"underestimated.\"\n- New estimate requested but not yet provided as of March 15.\n\n**March 14, 2024 - 9:00 AM**\n- Insurance company's loss assessor, Jennifer K. [Last name redacted],\ninspected facility.",
  "- Moisture mapping conducted in basement, second floor, and third floor.\n- Results pending (expected March 22, 2024).\n\n---\n\n## LOSS DETAILS & SUPPORTING EVIDENCE\n\n### **Property Damage Claim**\n\n**Reported Loss:** $287,500\n\n**Claimed Damage Components:**\n- Water-damaged equipment: $125,000 (detailed inventory list not\nprovided)\n- Ruined raw materials and work-in-progress inventory: $89,000 (no\nphotos, quantities unverified)\n- Flooring and structural repairs: $52,000 (quote from single contractor;",
  "000 (quote from single contractor;\nno competitive bids)\n- HVAC system replacement: $21,500 (claimed as \"necessary\" but original\nequipment age/condition unknown)\n\n**Assessment Status:** Awaiting moisture testing and structural engineer\nreport. Public adjuster disputes assessor's damage categorization.",
  "*\"Preliminary site inspection revealed inconsistencies between claimant's\naccount and physical evidence. Water patterns on second floor suggest\nlocalized damage, not facility-wide. Claimant provided conflicting\ntimeline regarding Feb seepage vs. March 12 primary event. Public\nadjuster present at inspection but did not cooperate with full\nassessment. Recommend: (1) Moisture mapping, (2) Plumbing inspection, (3)\nRoof structural assessment, (4) Financial records audit for BI claim. Do\nnot approve claim until cause of loss is determined.\""
],

[
  "- Claim described as \"catastrophic water damage affecting 60% of\nfacility.\"\n\n**March 13, 2024 - 2:15 PM**\n- Claimant's public adjuster, Mark T. [Last name redacted], appointed.\n- Public adjuster immediately disputed initial damage assessment as\n\"underestimated.\"\n- New estimate requested but not yet provided as of March 15.\n\n**March 14, 2024 - 9:00 AM**\n- Insurance company's loss assessor, Jennifer K. [Last name redacted],\ninspected facility.",
  "- West wall seepage (Feb) could be separate from overhead water (March\n12).\n   - Plumbing third floor not yet inspected.\n   - *Resolution needed: Plumbing assessment + structural inspection*\n\n2. **Extent of Damage Discrepancy:**\n   - Claimant claims 60% of facility affected.\n   - Insurance assessor estimates 15-20%.\n   - Public adjuster claims \"closer to 40%.\"\n   - *Resolution needed: Moisture mapping + structural survey*\n\n3.",
  "[Last name redacted],\ninspected facility.\n- Visual assessment only; no moisture readings taken at that time.\n- Assessor noted \"inconsistencies in claimant's account of water path.\"\n- Preliminary assessment: Damage confined to basement and small portion\nof second floor (estimated 15-20% of facility).\n\n**March 14, 2024 - 3:30 PM**\n- Claimant provided photographic evidence of water damage.",
  "- Moisture mapping conducted in basement, second floor, and third floor.\n- Results pending (expected March 22, 2024).\n\n---\n\n## LOSS DETAILS & SUPPORTING EVIDENCE\n\n### **Property Damage Claim**\n\n**Reported Loss:** $287,500\n\n**Claimed Damage Components:**\n- Water-damaged equipment: $125,000 (detailed inventory list not\nprovided)\n- Ruined raw materials and work-in-progress inventory: $89,000 (no\nphotos, quantities unverified)\n- Flooring and structural repairs: $52,000 (quote from single contractor;",
  "000 (quote from single contractor;\nno competitive bids)\n- HVAC system replacement: $21,500 (claimed as \"necessary\" but original\nequipment age/condition unknown)\n\n**Assessment Status:** Awaiting moisture testing and structural engineer\nreport. Public adjuster disputes assessor's damage categorization.",
  "- *Resolution needed: Moisture mapping + structural survey*\n\n3. **Timeline of Feb-March Events:**\n   - Feb repairs completed but details sparse.\n   - Feb seepage recurrence date unclear.\n   - Duration of Feb occupant displacement unknown.\n   - *Resolution needed: Maintenance records review + staff interviews*\n\n4. **Business Interruption Calculation:**\n   - March bank deposits ($67K) contradict loss claim ($100K).\n   - Partial production capacity March 16-27 not accounted for in claim."
],

[
  "Section: Decision and Outcome\n\nINSURANCE COMPANY RECOMMENDATIONS\n\nCurrent Status: CLAIM UNDER INVESTIGATION - NO PAYMENT AUTHORIZED\n\nRecommended Action: Do not approve full claim amount until:\n\n1. Roo...",
  "Section: Investigation Findings\n\nASSESSOR & ADJUSTER OBSERVATIONS\n\nInsurance Assessor Notes (Jennifer K., March 14)\n\n\"Preliminary site inspection revealed inconsistencies between claimant's account an...",
  "Section: Case Overview\n\nCOMMERCIAL PROPERTY INSURANCE CLAIM CASE FILE\nClaim #2024-CP-087456\nManufacturing Facility - Partial Water Damage & Business Interruption\n\nClaimant: Precision Manufacturing Ltd...",
  "Section: Claim Details\n\nLOSS DETAILS & SUPPORTING EVIDENCE\n\nProperty Damage Claim\n\nReported Loss: $287,500\n\nClaimed Damage Components:\n- Water-damaged equipment: $125,000 (detailed inventory list not ...",
  "Section: Medical Records\n\nMarch 12, 2024 - 6:30 AM\n- Morning shift supervisor discovered water pooling in basement mechanical room and on second-floor production area.\n- Immediate action: Power shut-o..."
],

[
  "Section: Incident Description\n\nCHRONOLOGICAL EVENT TIMELINE\n\nFebruary 2024 Events\n\nFebruary 3, 2024 - 10:15 AM\n- Building maintenance staff (name redacted in report) observed minor water seepage in ba...",
  "Section: Investigation Findings\n\nASSESSOR & ADJUSTER OBSERVATIONS\n\nInsurance Assessor Notes (Jennifer K., March 14)\n\n\"Preliminary site inspection revealed inconsistencies between claimant's account an...",
  "Section: Medical Records\n\nMarch 12, 2024 - 6:30 AM\n- Morning shift supervisor discovered water pooling in basement mechanical room and on second-floor production area.\n- Immediate action: Power shut-o...",
  "Section: Claim Details\n\nLOSS DETAILS & SUPPORTING EVIDENCE\n\nProperty Damage Claim\n\nReported Loss: $287,500\n\nClaimed Damage Components:\n- Water-damaged equipment: $125,000 (detailed inventory list not ...",
  "Section: Decision and Outcome\n\nINSURANCE COMPANY RECOMMENDATIONS\n\nCurrent Status: CLAIM UNDER INVESTIGATION - NO PAYMENT AUTHORIZED\n\nRecommended Action: Do not approve full claim amount until:\n\n1. Roo..."
],

 [
  "Section: Claim Details\n\nLOSS DETAILS & SUPPORTING EVIDENCE\n\nProperty Damage Claim\n\nReported Loss: $287,500\n\nClaimed Damage Components:\n- Water-damaged equipment: $125,000 (detailed inventory list not ...",
  "Section: Decision and Outcome\n\nINSURANCE COMPANY RECOMMENDATIONS\n\nCurrent Status: CLAIM UNDER INVESTIGATION - NO PAYMENT AUTHORIZED\n\nRecommended Action: Do not approve full claim amount until:\n\n1. Roo...",
  "Section: Investigation Findings\n\nASSESSOR & ADJUSTER OBSERVATIONS\n\nInsurance Assessor Notes (Jennifer K., March 14)\n\n\"Preliminary site inspection revealed inconsistencies between claimant's account an...",
  "Section: Case Overview\n\nCOMMERCIAL PROPERTY INSURANCE CLAIM CASE FILE\nClaim #2024-CP-087456\nManufacturing Facility - Partial Water Damage & Business Interruption\n\nClaimant: Precision Manufacturing Ltd...",
  "Section: Medical Records\n\nMarch 12, 2024 - 6:30 AM\n- Morning shift supervisor discovered water pooling in basement mechanical room and on second-floor production area.\n- Immediate action: Power shut-o..."
]
]
    
    # Optional: Ground truth answers if available
    ground_truths = [
        "March 15, 2024",
        "$387,500",
        "March 13, 2024, at 8:00 AM",      
        "March 12, 2024 at 2:47 AM.",
        "3 days, 8 hours, and 13 minutes.",
        "The exact purchase order number is PR-2847",
        "6:45 AM on March 12, 2024",
        "In that preliminary assessment, the loss assessor estimated that damage affected 15–20% of the facility"

    ]
    
    print("Running RAGAS evaluation with needle-in-a-haystack queries...")
    results = evaluate_rag_system(questions, answers, contexts, ground_truths)
    
    print("\n=== RAGAS Evaluation Results ===")
    print(results)
    
    return results


def evaluate_custom_rag_output(
    questions: List[str],
    rag_answers: List[str],
    rag_contexts: List[List[str]],
    ground_truths: List[str] = None
) -> Dict[str, float]:
    """
    Evaluate custom RAG system output with the needle-in-a-haystack queries.
    
    Args:
        questions: List of needle-in-a-haystack questions
        rag_answers: Answers generated by your RAG system
        rag_contexts: Contexts retrieved by your RAG system
        ground_truths: Optional ground truth answers
        
    Returns:
        Dictionary containing evaluation scores
    """
    return evaluate_rag_system(questions, rag_answers, rag_contexts, ground_truths)

def get_addional_answers():
    """
    Retrieve additional answers from the rag_specific_task_agent_results file.
    
    Returns:
        List of additional answers.
    """
    additional_answers = [
        "4 days, 9 hours, and 13 minutes.",
        "PO-2024-0205-WI",
        "6:45 AM on March 12, 2024",
        "The preliminary assessment estimated that damage affected 15–20% of the facility."
    ]

    # Lines 1-65: First string
    first_string = """### Insurance Claim Case Summary:

#### Case Overview:
- **Claimant:** Precision Manufacturing Ltd. (PML)
- **Policy Number:** CP-4827-2023
- **Claim Date Filed:** March 15, 2024
- **Incident Date:** March 12, 2024
- **Location:** 2847 Industrial Drive, Newark, NJ 07105
- **Claim Amount:** $387,500 (Under investigation)
- **Status:** Pending - Additional documentation required

#### Claim Details:
1. **Property Damage Claim:**
   - **Reported Loss:** $287,500
   - **Claimed Damage Components:**
     - Water-damaged equipment: $125,000
     - Ruined raw materials and inventory: $89,000
     - Flooring and structural repairs: $52,000
     - HVAC system replacement: $21,500
   - **Assessment Status:** Pending moisture testing and structural engineer report.

2. **Business Interruption Claim:**
   - **Reported Loss:** $100,000
   - **Period of Interruption:** March 12 - March 27, 2024
   - **Claimed Lost Revenue:** Represents lost sales during shutdown.
   - **Supporting Documentation Issues:** Lack of financial records, conflicting revenue data.

#### Investigation Findings:
- **Insurance Assessor Observations:**
  - Identified inconsistencies in claimant's account and evidence.
  - Recommended further assessments before claim approval.
- **Public Adjuster Statement:**
  - Asserted loss within policy limits, demanded immediate payment.
- **Claimant Statement:**
  - Urged prompt payment for severe and sudden damage.
  - Disagreement with assessment findings based on provided photos.

#### Insurance Company Recommendations:
- **Current Status:** Claim under investigation, no payment authorized.
- **Recommended Actions:** Pending resolution of key assessments and verifications.
- **Conditional Approval Thresholds:** Based on cause determination and assessment outcomes.
- **Estimated Timeline:** 3-4 weeks for resolution (subject to pending assessments).

### Key Insights:
1. **Discrepancies & Disputes:**
   - Conflicting accounts between claimant, assessor, and adjuster.
   - Lack of consensus on damage assessment and payment urgency.
2. **Documentation Deficiencies:**
   - Incomplete supporting evidence for claim components.
   - Missing financial records impacting business interruption claim validation.  
3. **Pending Assessments:**
   - Essential evaluations such as moisture testing and structural integrity assessment.
   - Resolution timeline contingent on completion of pending assessments.

### Actionable Steps:
1. **Documentation Review:**
   - Ensure detailed and accurate documentation for all claimed losses.
2. **Collaborative Assessment:**
   - Coordinate with all parties for thorough property damage and business interruption evaluations.
3. **Timely Resolution:**
   - Prioritize completion of pending assessments to expedite claim resolution.   
4. **Compliance Adherence:**
   - Follow insurance company recommendations and conditional approval thresholds for claim processing.

By addressing discrepancies, enhancing documentation, and expediting assessments, By addressing discrepancies, enhancing documentation, and expediting assessments, the insuthe insurance claim case for Precision Manufacturing Ltd. can move towards a comprehensive resolution within the estimated timeline."""

    # Lines 68-95: Second string
    second_string = """Here is a comprehensive summary of the major events from the initial February seepage observations to the anticipated resolution dates:

1. **February 2024 Events**:
   - **February 3, 2024 to February 22, 2024** (Duration: 19 days, 13 hours, 44 minutes):
     - Maintenance staff observed minor water seepage with no formal incident report filed.
     - Maintenance addressed water intrusion, and a roof inspection was reported.     
     - Water seepage reappeared, leading to building occupants' relocation and production loss.

2. **March 2024 Events**:
   - **March 12, 2024** (Primary Loss Event) (Duration: 19 days, 2 hours, 47 minutes):
     - Overnight water intrusion event discovered with the extent of damage unknown.  
     - Possible sources of water intrusion identified but no clear cause established. 

3. **Investigation Findings**:
   - **March 12, 2024 to March 14, 2024** (Duration: 2 days, 21 hours, 12 minutes):   
     - Inconsistencies between claimant's account and physical evidence noted.        
     - Recommendations for moisture mapping, plumbing inspection, and financial records audit made.

4. **Medical Response**:
   - **March 12, 2024** (Duration: 0 days, 4 hours, 0 minutes):
     - Water pooling discovered with a delay in calling an emergency response company.
     - Initial water removal and assessment started after the arrival of the response company.

5. **Overall Timeline Duration**:
   - From **February 3, 2024 to March 27, 2024** (Total: 53 days, 13 hours, 44 minutes):
     - Encompasses all major events from the initial observations to the anticipated resolution dates.

This summary provides a structured overview of the timeline of events, including inspections, reports, and claim-handling milestones, highlighting key periods and durations for each stage of the incident."""

    # Lines 97 to end: Third string
    third_string = """### Summary of Main Coverage, Documentation, and Causation Issues in the Claim Investigation:

#### 1. **Property Damage Claim Issues:**
- **Reported Loss:** $287,500
- **Claimed Damage Components:**
  - Water-damaged equipment: $125,000 (lack of detailed inventory list)
  - Ruined raw materials and inventory: $89,000 (no photos, unverified quantities)    
  - Flooring and structural repairs: $52,000 (quote from single contractor, no competitive bids)
  - HVAC system replacement: $21,500 (claimed as necessary, original equipment details unknown)
- **Assessment Status:** Awaiting moisture testing and structural engineer report; public adjuster disputes damage categorization.

#### 2. **Business Interruption Claim Issues:**
- **Reported Loss:** $100,000
- **Period of Interruption:** March 12 - March 27, 2024 (15 days, claimant's calculation)
- **Claimed Lost Revenue:** Represents lost sales during facility shutdown
- **Supporting Documentation Issues:**
  - Lack of monthly profit-and-loss statements
  - Absence of evidence for regular seasonal patterns
  - No documentation of canceled vs. deferred orders
  - Bank deposits for March contradict the $100,000 loss claim
  - Incomplete payroll records (only February full records provided)

#### 3. **Insurer's Recommended Actions and Conditional Approval Thresholds:**        
- **Current Status:** Claim under investigation; no payment authorized.
- **Recommended Actions:**
  - Establish root cause of water intrusion definitively
  - Confirm damage extent through moisture testing
  - Complete structural integrity assessment
  - Verify business interruption calculation against financial records
  - Confirm photo authenticity and maintenance compliance history
- **Conditional Approval Thresholds:**
  - Cause determination impacts coverage decision
  - Property damage claim approval within policy limits once cause is determined      
  - Business interruption claim reduction based on financial record conflicts
- **Estimated Timeline to Resolution:** 3-4 weeks contingent on pending assessments.  

#### 4. **Investigation Findings and Disputes:**
- **Assessor Observations:**
  - Inconsistencies between claimant's account and physical evidence
  - Conflicting timeline information
  - Recommendations for further assessments before claim approval
- **Public Adjuster Statement:**
  - Asserts loss is within policy limits, demands immediate payment
- **Claimant Statement:**
  - Claims good-faith customer history, requests immediate funds for operations restart.

### Impact on Insurer's Final Decision:

- **Documentation Issues:** Incomplete documentation may weaken the claim's validity and affect the final settlement amount.
- **Causation Disputes:** Determining the root cause of the water damage is crucial for coverage decisions.
- **Assessment Status:** Pending moisture testing and structural reports may delay the final decision.
- **Conditional Approval Thresholds:** Cause determination will dictate coverage amounts for property damage and business interruption.
- **Timeline to Resolution:** Estimated 3-4 weeks for a decision, subject to completion of pending assessments and resolution of disputes.

### Key Considerations for the Insurer:
- **Thorough Documentation:** Ensure all evidence and supporting documents are complete and consistent.
- **Causation Clarity:** Resolve disputes and determine the exact cause of loss for accurate coverage assessment.
- **Timely Assessments:** Expedite pending assessments to avoid prolonged claim processing.
- **Compliance with Policy Limits:** Adhere to conditional approval thresholds based on the investigation's outcomes.
- **Communication and Resolution:** Address disputes and conflicting statements to reach a fair and informed final decision."""

    # Create the list
    text_list = [first_string, second_string, third_string]

    return text_list

if __name__ == "__main__":
    # Run example evaluation
    try:
        results = run_example_evaluation()
    except ImportError as e:
        print(f"Error: {e}")
        print("\nTo use RAGAS, install required packages:")
        print("pip install ragas datasets")
    except Exception as e:
        print(f"Error during evaluation: {e}")
        import traceback
        traceback.print_exc()
