"""
Test file for Summarization Expert Agent with ChromaDB

This script:
1. Connects to ChromaDB
2. Gets a broad question from the user
3. Retrieves relevant contexts from ChromaDB
4. Executes the summarization expert agent
5. Prints the contexts retrieved from ChromaDB
6. Prints the final answer generated by the agent
"""

import os
from dotenv import load_dotenv
import chromadb
from summarization_expert_agent import SummarizationExpertAgent

# Load environment variables
load_dotenv()


def print_separator(title: str = ""):
    """Print a formatted separator line."""
    if title:
        print(f"\n{'=' * 70}")
        print(f"  {title}")
        print(f"{'=' * 70}\n")
    else:
        print(f"{'=' * 70}\n")


def initialize_chromadb():
    """Initialize ChromaDB client and collection."""
    print("🔧 Connecting to ChromaDB...")
    try:
        client = chromadb.PersistentClient(path="./chroma_db")
        collection = client.get_or_create_collection(name="insurance_claims")
        doc_count = collection.count()
        print(f"✅ Connected: {doc_count} documents in collection\n")
        
        if doc_count == 0:
            print("⚠️  Warning: No documents found in ChromaDB!")
            print("💡 Run 'python chromadb_chunk_pdf.py' first to process your PDF.\n")
            return None
            
        return collection
    except Exception as e:
        print(f"❌ Error connecting to ChromaDB: {str(e)}\n")
        return None


def print_retrieved_contexts(collection, user_question: str, n_results: int = 5):
    """
    Retrieve and print contexts from ChromaDB.
    
    Args:
        collection: The ChromaDB collection
        user_question: The user's question to retrieve contexts for
        n_results: Number of results to retrieve
        
    Returns:
        List of context strings
    """
    print_separator("RETRIEVED CONTEXTS FROM CHROMADB")
    
    print(f"🔍 Query: {user_question}\n")
    print(f"Retrieving top {n_results} relevant contexts from ChromaDB...\n")
    
    try:
        # Query ChromaDB for relevant chunks
        results = collection.query(
            query_texts=[user_question],
            n_results=n_results,
            include=["documents", "metadatas", "distances"]
        )
        
        if not results['documents'][0]:
            print("⚠️  No relevant contexts found in ChromaDB.\n")
            return []
        
        print(f"✅ Retrieved {len(results['documents'][0])} chunk(s)\n")
        
        # Extract contexts with metadata
        contexts = []
        for i, (doc, metadata, distance) in enumerate(zip(
            results['documents'][0],
            results['metadatas'][0],
            results['distances'][0]
        )):
            contexts.append(doc)
            relevance_score = 1 - distance  # Convert distance to similarity
            title = metadata.get('title', 'Unknown')
            print(f"  Chunk {i+1}: {title} (relevance: {relevance_score:.3f})")
        
        print()
        
        # Print contexts as a formatted list
        print("Contexts: [")
        for i, context in enumerate(contexts):
            # Add comma separator between contexts
            separator = "," if i < len(contexts) - 1 else ""
            # Truncate long contexts for display
            display_context = context[:200] + "..." if len(context) > 200 else context
            print(f'  "{display_context}"{separator}')
        print("]\n")
        
        return contexts
        
    except Exception as e:
        print(f"❌ Error retrieving contexts: {str(e)}\n")
        return []


def main():
    """Main function to test the Summarization Expert Agent."""
    print_separator("SUMMARIZATION EXPERT AGENT - TEST MODE")
    
    # Check for OpenAI API key
    if not os.getenv("OPENAI_API_KEY"):
        print("⚠️  Warning: OPENAI_API_KEY not found in environment variables.")
        api_key = input("\nEnter your OpenAI API key (or press Enter to skip): ").strip()
        if api_key:
            os.environ["OPENAI_API_KEY"] = api_key
        else:
            print("\n❌ Cannot proceed without OpenAI API key. Exiting...\n")
            return
    
    try:
        # Step 1: Connect to ChromaDB
        print_separator("STEP 1: CONNECTING TO CHROMADB")
        
        collection = initialize_chromadb()
        
        if not collection:
            print("\n❌ Cannot proceed without ChromaDB connection. Exiting...\n")
            return
        
        print("✅ ChromaDB connection ready!\n")
        
        # Step 2: Get question from user
        print_separator("STEP 2: GET USER QUESTION")
        
        print("Enter your broad question about the insurance claim document.")
        print("Examples:")
        print("  - Summarize the entire insurance claim case")
        print("  - What are the key events in the timeline?")
        print("  - Give me an overview of this claim")
        print("  - What were the main findings and outcomes?")
        print("  - Who are all the parties involved?")
        print()
        
        user_question = input("Your question: ").strip()
        
        if not user_question:
            print("\n⚠️  No question provided. Using default question.\n")
            user_question = "Summarize the insurance claim case"
        
        print(f"\n📝 Question: {user_question}\n")
        
        # Step 3: Print retrieved contexts
        print_separator("STEP 3: RETRIEVE CONTEXTS FROM CHROMADB")
        contexts = print_retrieved_contexts(collection, user_question, n_results=5)
        
        if not contexts:
            print("⚠️  No contexts retrieved. Agent may not be able to answer.\n")
        
        # Step 4: Initialize and execute the agent
        print_separator("STEP 4: EXECUTE SUMMARIZATION EXPERT AGENT")
        
        print("Initializing Summarization Expert Agent...\n")
        agent = SummarizationExpertAgent(
            model_name="gpt-3.5-turbo",
            temperature=0.7
        )
        
        print("Processing question with the agent...\n")
        
        # Build context from retrieved chunks
        context = "\n\n---\n\n".join([
            f"Section {i+1}:\n{chunk}"
            for i, chunk in enumerate(contexts)
        ]) if contexts else None
        
        # Execute the agent
        answer = agent.process_broad_question(user_question, context=context)
        
        # Step 5: Print the final answer
        print_separator("STEP 5: FINAL ANSWER")
        
        print("🤖 Agent Answer:\n")
        print(answer)
        print()
        
        # Summary
        print_separator("SUMMARY")
        print(f"✅ Question: {user_question}")
        print(f"✅ Contexts Retrieved: {len(contexts)}")
        print(f"✅ Answer Generated: Yes")
        print()
        
        # Option to ask another question
        print_separator()
        while True:
            another = input("Would you like to ask another question? (y/n): ").strip().lower()
            
            if another in ['n', 'no']:
                print("\n👋 Thank you for using the Summarization Expert Agent!\n")
                break
            elif another in ['y', 'yes']:
                print()
                user_question = input("Your question: ").strip()
                
                if not user_question:
                    print("\n⚠️  No question provided. Exiting...\n")
                    break
                
                print(f"\n📝 Question: {user_question}\n")
                
                # Print retrieved contexts
                print_separator("RETRIEVED CONTEXTS")
                contexts = print_retrieved_contexts(collection, user_question, n_results=5)
                
                # Build context
                context = "\n\n---\n\n".join([
                    f"Section {i+1}:\n{chunk}"
                    for i, chunk in enumerate(contexts)
                ]) if contexts else None
                
                # Execute the agent
                print_separator("AGENT PROCESSING")
                answer = agent.process_broad_question(user_question, context=context)
                
                # Print the final answer
                print_separator("FINAL ANSWER")
                print("🤖 Agent Answer:\n")
                print(answer)
                print()
            else:
                print("Please enter 'y' or 'n'")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}\n")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
