"""
Test file for Specific Task Expert Agent with Hierarchical Retrieval

This script:
1. Builds the hierarchical auto-merging retrieval system
2. Gets a question from the user
3. Executes the specific task expert agent
4. Prints the contexts retrieved from the vector store
5. Prints the final answer generated by the agent
"""

import os
from dotenv import load_dotenv
from specific_task_expert_agent import SpecificTaskExpertAgent
from hierarchical_retriever import get_claim_retriever

# Load environment variables
load_dotenv()


def print_separator(title: str = ""):
    """Print a formatted separator line."""
    if title:
        print(f"\n{'=' * 70}")
        print(f"  {title}")
        print(f"{'=' * 70}\n")
    else:
        print(f"{'=' * 70}\n")


def print_retrieved_contexts(retriever, user_question: str):
    """
    Retrieve and print contexts from the vector store.
    
    Args:
        retriever: The hierarchical auto-merging retriever
        user_question: The user's question to retrieve contexts for
    """
    print_separator("RETRIEVED CONTEXTS FROM VECTOR STORE")
    
    print(f"🔍 Query: {user_question}\n")
    print("Retrieving relevant contexts using hierarchical auto-merging retrieval...\n")
    
    try:
        # Retrieve nodes using the hierarchical retriever
        retrieved_nodes = retriever.retrieve(user_question)
        
        if not retrieved_nodes:
            print("⚠️  No relevant contexts found in the vector store.\n")
            return []
        
        print(f"✅ Retrieved {len(retrieved_nodes)} node(s) after auto-merging\n")
        
        # Extract only the text from each retrieved context
        contexts = [node.text for node in retrieved_nodes]
        
        # Print contexts as a formatted list
        print("Contexts: [")
        for i, context in enumerate(contexts):
            # Add comma separator between contexts
            separator = "," if i < len(contexts) - 1 else ""
            print(f'  "{context}"{separator}')
        print("]\n")
        
        return contexts
        
    except Exception as e:
        print(f"❌ Error retrieving contexts: {str(e)}\n")
        return []


def main():
    """Main function to test the Specific Task Expert Agent."""
    print_separator("SPECIFIC TASK EXPERT AGENT - TEST MODE")
    
    # Check for OpenAI API key
    if not os.getenv("OPENAI_API_KEY"):
        print("⚠️  Warning: OPENAI_API_KEY not found in environment variables.")
        api_key = input("\nEnter your OpenAI API key (or press Enter to skip): ").strip()
        if api_key:
            os.environ["OPENAI_API_KEY"] = api_key
        else:
            print("\n❌ Cannot proceed without OpenAI API key. Exiting...\n")
            return
    
    try:
        # Step 1: Build the hierarchical retrieval system
        print_separator("STEP 1: BUILDING HIERARCHICAL RETRIEVAL SYSTEM")
        
        print("Building hierarchical auto-merging retriever...")
        print("(This may take a moment on first run)\n")
        
        # Get the retriever (uses in-memory vector store by default)
        retriever = get_claim_retriever(use_supabase=False)
        
        print("\n✅ Hierarchical retrieval system ready!\n")
        
        # Step 2: Get question from user
        print_separator("STEP 2: GET USER QUESTION")
        
        print("Enter your question about the insurance claim document.")
        print("Examples:")
        print("  - What is the claim number?")
        print("  - When was the incident date?")
        print("  - How many days elapsed between the incident and claim filing?")
        print("  - What is the claim amount?")
        print("  - Who is the policyholder?")
        print()
        
        user_question = input("Your question: ").strip()
        
        if not user_question:
            print("\n⚠️  No question provided. Using default question.\n")
            user_question = "What is the claim number?"
        
        print(f"\n📝 Question: {user_question}\n")
        
        # Step 3: Print retrieved contexts
        print_separator("STEP 3: RETRIEVE CONTEXTS")
        contexts = print_retrieved_contexts(retriever, user_question)
        
        # Step 4: Initialize and execute the agent
        print_separator("STEP 4: EXECUTE SPECIFIC TASK EXPERT AGENT")
        
        print("Initializing Specific Task Expert Agent...\n")
        agent = SpecificTaskExpertAgent(
            model_name="gpt-3.5-turbo",
            temperature=0,
            use_hierarchical_retrieval=True
        )
        
        print("Processing question with the agent...\n")
        
        # Execute the agent
        answer = agent.process_specific_question(user_question)
        
        # Step 5: Print the final answer
        print_separator("STEP 5: FINAL ANSWER")
        
        print("🤖 Agent Answer:\n")
        print(answer)
        print()
        
        # Summary
        print_separator("SUMMARY")
        print(f"✅ Question: {user_question}")
        print(f"✅ Contexts Retrieved: {len(contexts)}")
        print(f"✅ Answer Generated: Yes")
        print()
        
        # Option to ask another question
        print_separator()
        while True:
            another = input("Would you like to ask another question? (y/n): ").strip().lower()
            
            if another in ['n', 'no']:
                print("\n👋 Thank you for using the Specific Task Expert Agent!\n")
                break
            elif another in ['y', 'yes']:
                print()
                user_question = input("Your question: ").strip()
                
                if not user_question:
                    print("\n⚠️  No question provided. Exiting...\n")
                    break
                
                print(f"\n📝 Question: {user_question}\n")
                
                # Print retrieved contexts
                print_separator("RETRIEVED CONTEXTS")
                contexts = print_retrieved_contexts(retriever, user_question)
                
                # Execute the agent
                print_separator("AGENT PROCESSING")
                answer = agent.process_specific_question(user_question)
                
                # Print the final answer
                print_separator("FINAL ANSWER")
                print("🤖 Agent Answer:\n")
                print(answer)
                print()
            else:
                print("Please enter 'y' or 'n'")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}\n")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
